services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: menu-cr-db

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Sapphire123!"

    ports:
      - "1433:1433"

    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: